services:
  postgres:
    container_name: 'backend-db'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=backend'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '6420:5432'